// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
}

declare namespace NodeJS {
  interface ProcessEnv {
    ZHIPU_API_KEY: string;
  }
}
